### PR TITLE
Starting in tab

### PR DESCRIPTION
**Pull request by AlvarHHM**
ちょっとやってみたんですが、如何？

Image 1
Image 2
Image 3

### CODE REVIEW

**Comment by akirattii** [comment]
お、これいいですね♪
マージさせてもらいますね。
ありがとうございます。

**Comment by AlvarTheCoder** [comment]
you are welcome, this indeed is a pretty good application for browsing 2ch

**Comment by AlvarTheCoder** [comment]
Please translate the english description to Japanese in the setting page

**Comment by akirattii** [comment]
@AlvarTheCoder 
Oh, thanks for pointing out to me. 
OK, I'll translate it in a bit.

**Pull request merged**
